#pragma config(Sensor, dgtl7,  leftEncoder,    sensorRotation)
#pragma config(Sensor, dgtl8,  rightEncoder,   sensorRotation)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Moving Straight with Encoders -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program implements a self-straightening algorithm that provides a higher power level to the  *|
|*  motor that has traveled less, determined by comparing the values of the two encoders.             *|
|*  There is a 2 second pause at the beginning of the program.                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 8  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 7  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/

//611° == 0.55M
//160° == 90°
//int rotationConstant = 1.66;

int driveInstructions[7] = {300, 0, 300, 0, 300, 0, 300};
int rotateInstructions[7] = {0, -90, 0, 90, 0, 90, 0};


float rotationConstant = 1.66;

void Rotate(int degrees)
{

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	if(degrees > 0)
	{
		while(SensorValue[rightEncoder] < degrees * rotationConstant)
		{
			motor[rightMotor] = -70;
			motor[leftMotor] = 70;
		}
	}
	else
	{
		while(SensorValue[rightEncoder] < -degrees * rotationConstant)
		{
			motor[rightMotor] = 80;
			motor[leftMotor] = -80;
		}
	}
}

void Drive(int dist, bool backforw)
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(dist > SensorValue[rightEncoder])
	{
		int i = 0;

		if (backforw == true)
		{
			i = 1;
		}
		else
		{
			i = -1;
		}

		if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
		{
			// Move Forward
			motor[rightMotor] = 80 * i;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 80 * i;		    // Left Motor is run at power level 80
		}
		else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])	// If rightEncoder has counted more encoder counts
		{
			// Turn slightly right
			motor[rightMotor] = 60 * i;		    // Right Motor is run at power level 60
			motor[leftMotor]  = 80 * i; 	    // Left Motor is run at power level 80
		}
		else	// Only runs if leftEncoder has counted more encoder counts
		{
			// Turn slightly left
			motor[rightMotor] = 80 * i;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 60 * i;		    // Left Motor is run at power level 60
		}
	}
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	for(int i = 0; i < 7; i++)
	{
		Drive(driveInstructions[i], true);
		motor[rightMotor] = 0;		    // Right Motor is run at power level 80
	  motor[leftMotor]  = 0;
	  wait1Msec(200);
		Rotate(rotateInstructions[i]);
		motor[rightMotor] = 0;		    // Right Motor is run at power level 80
	  motor[leftMotor]  = 0;
	  wait1Msec(200);

	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
