#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    lineFollower1,  sensorLineFollower)
#pragma config(Sensor, in2,    lineFollower2,  sensorLineFollower)
#pragma config(Sensor, in3,    lineFollower3,  sensorLineFollower)
#pragma config(Sensor, in4,    lightSensor,    sensorReflection)
#pragma config(Sensor, in8,    potentioMeter,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, dgtl2,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl10, leftEncoder,    sensorRotation)
#pragma config(Sensor, dgtl12, rightEncoder,   sensorRotation)
#pragma config(Motor,  port2,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <functions_V6.c>

/*-----------------------------------------------------------------------------------------------------*\
|*                                         	 - Verkefni 6 -                                          	 *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                       *|
|*                                                                                                     *|
|*  The vex only starts once one of the linefollowers detect a value above 2800. vex then follows      *|
|* that value and if it goes of course it will automaticly rotate towards the angle that lost the line *|
\*-----------------------------------------------------------------------------------------------------*/

int lightSens = SensorValue(lightSensor);
int sonarval = SensorValue(sonar1);
int folow1 = SensorValue(lineFollower1);
int folow2 = SensorValue(lineFollower2);
int folow3 = SensorValue(lineFollower3);

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	motor[clawMotor] = 127;
	wait1Msec(1000);
	motor[clawMotor] = 0;
	motor[armMotor] = 15;
  while(EmergencyButtons() == false)
  {
    if (lightSensor < 400)
    {
      sonarval = SensorValue(sonar1);
    	folow1 = SensorValue(lineFollower1);
	  	folow2 = SensorValue(lineFollower2);
	  	folow3 = SensorValue(lineFollower3);
	  	lightSens = SensorValue(lightSensor);

	    if(SensorValue(lineFollower1) > threshold || SensorValue(lineFollower2) > threshold || SensorValue(lineFollower3) > threshold)
	    {
	    	Linefollow();
	  	}
	  	else if(SensorValue(lineFollower1) < threshold && SensorValue(lineFollower2) < threshold && SensorValue(lineFollower3) < threshold)
	  	{
	  	 GrabAndTwist();
      }
    }
    else
    {
    	Stop();
    }
  }
}
